spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:haruDB;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: create
        use_sql_comments: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
